#cloud-config

autoinstall:

  shutdown: poweroff

  updates: all

  user-data:

    # if pc is notebook, make it sure to disable lid action (like suspend when lid is closed)
    # after this reboot needed
    # or this sudo service systemd-logind restart
    runcmd:
      - |
        sed -i \
          -e 's|.*HandleLidSwitch=.*$|HandleLidSwitch=ignore|g' \
          -e 's|.*LidSwitchIgnoreInhibited.*$|LidSwitchIgnoreInhibited=no|g' \
          /etc/systemd/logind.conf


    # runcmd:
    #   - |
    #     mkdir -p /etc/cloud/ || true
    #     touch /etc/cloud/cloud-init.disabled
    #     touch /home/admin/cloud-init.disabled
    #     touch /opt/fafa.disabled

    # power_state:
    #   mode: poweroff
    #   message: Byeeeeeeeee
    #   condition: true

    write_files:
    - content: |
        cloud_init_has_run
      path: /cloud_init_flag
    - content: |
        # Disable cloud-init after successful install
      path: /etc/cloud/cloud-init.disabled

  # apt:
  #   geoip: true
  #   preserve_sources_list: false
  #   primary:
  #   - arches: [amd64, i386]
  #     uri: http://hu.archive.ubuntu.com/ubuntu
  #   - arches: [default]
  #     uri: http://ports.ubuntu.com/ubuntu-ports
  identity:
    hostname: ubuntu-autoinstaller
    # echo fafa | mkpasswd -m sha-512 -s
    # password: "$6$X/rLB/BbkccYMf61$QFcxTazvsVxrYDOgmcM4j7w3CoilujvuE56jNg/TCY1J7jdicv87WQBZCNF98enCDQyrq.VZScJOC5ehBceJv."
    # password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
    # password: "$6$lTRfUI2RaI$RzKot9tnRsalQPOOdNciyj3yt/MBR3bsOEbE8tn/Z1p4VpcH1MZKbyIJeaAtHpjrIv8UleqkD9dABygwJTMdy."
    # password: "$6$1eh7bcxXgqIcA517$KJysFy.us8LgqO2xB8Sz8WTxGE1bpT4M12GOR9Te2y3UKX2pxVKtq/UDYEFeoD7YMm1ciK992EjAfixTzF4ZD1"
    # username: smapplab
    username: admin
    password: "$6$Bqh6e2XaWS/BP0oN$tIbGMdH.Ds/cnANOeWtQGs7jlslHkdhk2NB9Ydz7/cIJm8HHpsZjWbmFHQ7eqiR5zWSQwShR7NUVfA1Efkk0t1"
  keyboard:
    layout: hu
    # variant: hu
  locale: hu_HU
  # - vim
  packages:
  - curl
  - neovim
  - htop
  - iotop
  - tmux
  ssh:
    install-server: true
    allow-pw: false
    authorized-keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICgcJfi0dZotMWa8zQvxXduM76GmQfoPvMU5FjIFZCAa alfonzso@gmail.com
  storage:
    layout:
      name: lvm
      # match:
      #   ssd: yes

  # reporting:
  #   central:
  #     type: rsyslog
  #     destination: "@192.168.1.101"
  # reporting:
  #   hook:
  #     type: webhook
  #     endpoint: http://192.168.1.101:5000/webhook
  #     consumer_key: "ck_foo"
  #     consumer_secret: "cs_foo"
  #     token_key: "tk_foo"
  #     token_secret: "tk_secret"
  #     level: INFO
  version: 1
